name: Processo para o ecr

on:
  workflow_call:
    inputs:
        environment:
          required: true
          type: string

jobs:
  push_to_ecr:
    name: Criação da imagem no ECR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configurando as credenciais na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Compilando data atual
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Criando backup da imagem atual
        run: |
          if aws ecr describe-images --repository-name ${{ secrets.ECR_IMAGE }} --image-ids imageTag=latest > /dev/null 2>&1; then
            docker pull ${{ secrets.ECR_IMAGE }}
            docker image tag ${{ secrets.ECR_IMAGE }} ${{ secrets.ECR_IMAGE }}_${{ steps.date.outputs.date }}
            docker push ${{ secrets.ECR_IMAGE }}_${{ steps.date.outputs.date }}
          else
            echo "Imagem não encontrada no ECR, backup ignorado."
          fi

      - name: Preparando e enviando imagem para o Amazon ECR
        run: |
          docker build -t ${{ secrets.ECR_IMAGE }} -f ${{ vars.DOCKER_FILE }} ..
          docker push ${{ secrets.ECR_IMAGE }}
