name: Publicação para EC2

on:
  workflow_call:
    inputs:
      DOCKER_FILE:
        required: true
        type: string
      DOCKER_COMPOSE_FILE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ECR_IMAGE:
        required: true
      VERSION_SUFFIX:
        required: true
      AWS_ORGANIZATION:
        required: true
      AWS_SERVER:
        required: true
      AWS_SERVER_USER:
        required: true
      AWS_SSH_KEY:
        required: true

jobs:
  push_to_ecr:
    uses: nimblersoftware/actions/.github/workflows/publishing-to-ecr-v1.yml@master
    with:
      DOCKER_FILE: ${{ inputs.DOCKER_FILE }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_IMAGE: ${{ secrets.ECR_IMAGE }}
      VERSION_SUFFIX: ${{ secrets.VERSION_SUFFIX }}

  deploy:
    name: Publicação AWS EC2
    runs-on: ubuntu-latest
    needs: push_to_ecr
    steps:
      - name: Efetuando publicação
        uses: appleboy/ssh-action@v1.2.0 #appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_SERVER }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo su
            cd docker-compose
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ORGANIZATION }}
            docker-compose -f ${{ inputs.DOCKER_COMPOSE_FILE }} down
            docker rmi -f $(docker images -a -q)
            docker-compose -f ${{ inputs.DOCKER_COMPOSE_FILE }} up -d
