name: Publicação de pacotes node
on:
  workflow_call:
    inputs:
        PROJECT_NAME:
            required: true
            type: string
        WORKING_DIRECTORY:
            required: true
            type: string
        DIST_DIRECTORY:
            required: true
            type: string
        RUN_COMMAND:
            required: true
            type: string
    secrets:
        NODE_VERSION:
            required: true
        GIT_TOKEN:
            required: true
jobs:
  build:
    name: Compilando pacote ${{ inputs.PROJECT_NAME }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v4
      - name: Setando versão do Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nimblersoftware'

      - name: Restaurando dependências
        run: npm i -f

      - name: Compilando projeto
        run: ${{ inputs.RUN_COMMAND }}

      - name: Exclusão do pacote no nuget
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ inputs.PROJECT_NAME }}
          token: ${{ secrets.GIT_TOKEN }}
          package-type: npm

      - name: Publicando pacote
        run: |
          cd ${{ inputs.DIST_DIRECTORY }}
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}